require("prototypes.generator")
require("prototypes.biters")
require("prototypes.incubator")
require("prototypes.revitalization-center")
require("prototypes.buried-biter-nest")
require("prototypes.biter-relocation-center")